<bug>
          <bug_id>2878</bug_id>
          
          <creation_ts>2009-10-01 11:28:00 +0200</creation_ts>
          <short_desc>Wrong package for ScriptTransport</short_desc>
          <delta_ts>2009-10-07 10:57:04 +0200</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>contrib</product>
          <component>RpcPhp</component>
          <version>unspecified</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>trivial</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Dominik Horb">dominik.horb</reporter>
          <assigned_to name="Derrell Lipman">derrell.lipman</assigned_to>
          
          <qa_contact name="Derrell Lipman">derrell.lipman</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>12782</commentid>
            <who name="Dominik Horb">dominik.horb</who>
            <bug_when>2009-10-01 11:28:44 +0200</bug_when>
            <thetext>Hi,
I&#39;m using qooxdoo 0.8.3 with the current Trunk version of RpcPHP. 

When I call the echo method of the test class via:

callRpcServer : function ()
    {
      var rpc = new qx.io.remote.Rpc();
      rpc.setTimeout(1000000);
      rpc.setUrl(&quot;http://127.0.0.1/services/&quot;);
      rpc.setCrossDomain(true);
      rpc.setServiceName(&quot;qooxdoo.test&quot;);
      // asynchronous call
      var handler = function(result, exc) {
          if (exc == null) {
              alert(&quot;Result of async call: &quot; + result);
          } else {
              alert(&quot;Exception during async call: &quot; + exc);
          }
      };
      var array = new Array(&#39;asdfas&#39;);
      rpc.callAsync(handler, &quot;echo&quot;, array);
    }

The result is an alert with a timeout notice. I tracked the Http header and checked out the result of the url which gives:

qx.remote.ScriptTransport._requestFinished(1, {&quot;result&quot;:&quot;Client said: [Array]&quot;,&quot;id&quot;:1});

So everything seems to be fine. The problem with this is, that the returned class doesn&#39;t exist. In my opinion this should be:

qx.io.remote.ScriptTransport [...]

If I change this in AbstractServer.php on line 1045 everything works fine.

Best Regards,

Dominik</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>12784</commentid>
            <who name="Andreas Ecker">qooxdoo</who>
            <bug_when>2009-10-01 13:11:13 +0200</bug_when>
            <thetext>Thanks Dominik, assigned to Derrell.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>12794</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2009-10-01 14:48:52 +0200</bug_when>
            <thetext>Fixed with r19302. Thanks! Please confirm the fix and then mark this bug as verified.

Derrell
</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>12795</commentid>
            <who name="Dominik Horb">dominik.horb</who>
            <bug_when>2009-10-01 15:15:18 +0200</bug_when>
            <thetext>Seems fine, thx for the fast fix.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>12899</commentid>
            <who name="Andreas Ecker">qooxdoo</who>
            <bug_when>2009-10-07 10:57:04 +0200</bug_when>
            <thetext>closed</thetext>
          </long_desc>
      
      

    </bug>