<bug>
          <bug_id>2930</bug_id>
          
          <creation_ts>2009-10-14 17:38:00 +0200</creation_ts>
          <short_desc>&quot;create-application.py -t contribution&quot; doesn&#39;t build properly</short_desc>
          <delta_ts>2009-10-15 17:33:16 +0200</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>INVALID</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Derrell Lipman">derrell.lipman</reporter>
          <assigned_to name="Unassigned">none</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>13189</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2009-10-14 17:38:50 +0200</bug_when>
            <thetext>I want to create a new contrib, so I typed:

  /home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/bin/create-application.py -n qooxit -t contribution

I then changed into the trunk directory and edited the QOOXDOO_PATH entry in config.json:

    &quot;QOOXDOO_PATH&quot; : &quot;../../../../../trunk/qooxdoo&quot;,

and then with no other changes, ran &quot;generate.py source&quot; which yielded this:

{dworkin} /home/derrell/ME/qooxdoo.git/qooxdoo-contrib/trunk/qooxdoo-contrib/qooxit/trunk ---&gt; ./generate.py source

============================================================================
    INITIALIZING: TRUNK
============================================================================
&gt;&gt;&gt; Configuration: config.json
&gt;&gt;&gt; Jobs: source
&gt;&gt;&gt; Resolving config includes...
&gt;&gt;&gt; Resolving jobs...
&gt;&gt;&gt; Incorporating job defaults...
&gt;&gt;&gt; Resolving macros...
&gt;&gt;&gt; Resolving libs/manifests...

============================================================================
    EXECUTING: SOURCE::SOURCE-SCRIPT
============================================================================
&gt;&gt;&gt; Scanning libraries...
  - Scanning /home/derrell/ME/qooxdoo.git/qooxdoo-contrib/trunk/qooxdoo-contrib/qooxit/trunk...
!!! Invalid include block: [u&#39;qx.theme.Modern&#39;, u&#39;qooxit.demo.Demo&#39;]
Traceback (most recent call last):
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/bin/generator.py&quot;, line 165, in &lt;module&gt;
    main()
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/bin/generator.py&quot;, line 160, in main
    generatorObj.run()
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/pylib/generator/Generator.py&quot;, line 485, in run
    includeWithDeps, includeNoDeps = getIncludes(self._job.get(&quot;include&quot;, []))
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/pylib/generator/Generator.py&quot;, line 361, in getIncludes
    includeWithDeps = self._expandRegExps(includeWithDeps)
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/pylib/generator/Generator.py&quot;, line 1319, in _expandRegExps
    expanded = self._expandRegExp(entry, container)
  File &quot;/home/derrell/ME/qooxdoo.git/trunk/qooxdoo/tool/pylib/generator/Generator.py&quot;, line 1337, in _expandRegExp
    raise RuntimeError, &quot;Expression gives no results. Malformed entry: %s&quot; % entry
RuntimeError: Expression gives no results. Malformed entry: qooxit.demo.Demo</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>13190</commentid>
            <who name="Derrell Lipman">derrell.lipman</who>
            <bug_when>2009-10-14 17:41:34 +0200</bug_when>
            <thetext>And then Christian piped in with this gem:

&quot;I already mentioned this, but maybe only in a private Email to Andreas -
there is a mismatch between the application name &quot;demo.Demo&quot; in the
config.json and &quot;demo.Application&quot; in the file system (or the other way
round)...&quot;
</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>13218</commentid>
            <who name="Andreas Ecker">qooxdoo</who>
            <bug_when>2009-10-15 17:33:16 +0200</bug_when>
            <thetext>Hi Derrell,

seems like there are 2 misconceptions about the current implementation:

1) the QOOXDOO_PATH provided in the contribution skeleton isn&#39;t needed to be adjusted within a qooxdoo-contrib checkout. It obviously cannot account (i.e. being checked in) for an individual file system layout, so this kind of mapping is done elsewhere (via symbolic links) by each user. Please see the README.txt in folder qooxdoo/ of your qooxdoo-contrib checkout.

2) the actual applications that you&#39;d run the typical generator targets for are the demos of a contribution, see the demo/ folder of your contrib. The top-level generate.py is still a placeholder for future targets that would make sense on a top-level, e.g. for zipping a contrib or generating all demos at once. For the time being, just ignore the top-level generate (or feel free to remove it).

Anyway, the contribution skeleton should run out-of-the-box, at least this was the experience for all recent contribs. If you&#39;ve got questions/feedback, we could both figure out things in a chat.

</thetext>
          </long_desc>
      
      

    </bug>