<bug>
          <bug_id>4366</bug_id>
          
          <creation_ts>2010-11-24 21:52:00 +0100</creation_ts>
          <short_desc>Easier debugging of rpc calls.</short_desc>
          <delta_ts>2010-12-13 08:36:53 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>core.io.remote</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>enhancement</bug_severity>
          <target_milestone>1.3</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Fritz Zaucker">fritz.zaucker</reporter>
          <assigned_to name="Martin Wittemann">martin.wittemann</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>21544</commentid>
            <who name="Fritz Zaucker">fritz.zaucker</who>
            <bug_when>2010-11-24 21:52:08 +0100</bug_when>
            <thetext>Debugging timed-out or aborted rpc calls would be a lot easier if the error message would contain the name of the method being called. 

Therefore I&#39;d like to suggest the following trivial patch.

Cheers,
Fritz

--- Rpc.js.orig 2010-07-09 14:58:18.000000000 +0200
+++ Rpc.js      2010-11-24 21:48:05.000000000 +0100
@@ -564,7 +564,7 @@
         this.debug(&quot;TIMEOUT OCCURRED&quot;);
         ex = makeException(qx.io.remote.Rpc.origin.local,
                            qx.io.remote.Rpc.localError.timeout,
-                           &quot;Local time-out expired&quot;);
+                           &quot;Local time-out expired for &quot; + whichMethod);
         id = this.getSequenceNumber();
         handleRequestFinished(&quot;timeout&quot;, eventTarget);
       });
@@ -573,7 +573,7 @@
       {
         ex = makeException(qx.io.remote.Rpc.origin.local,
                            qx.io.remote.Rpc.localError.abort,
-                           &quot;Aborted&quot;);
+                           &quot;Aborted &quot; + whichMethod);
         id = this.getSequenceNumber();
         handleRequestFinished(&quot;aborted&quot;, eventTarget);
       });</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>21547</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2010-11-25 09:19:08 +0100</bug_when>
            <thetext>Looks like a reasonable and easy one. Will fix that next week for the upcoming release. Thanks for the report!</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>21557</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2010-11-25 13:43:50 +0100</bug_when>
            <thetext>Applied the patch with r23986.</thetext>
          </long_desc>
      
      

    </bug>