<bug>
          <bug_id>5585</bug_id>
          
          <creation_ts>2011-09-05 11:48:00 +0200</creation_ts>
          <short_desc>tool error in Locale.py: &#39;unicode&#39; object has no attribute id</short_desc>
          <delta_ts>2014-03-03 15:21:10 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P2</priority>
          <bug_severity>major</bug_severity>
          <target_milestone>1.6</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Uwe Stahl">uwe.stahl</reporter>
          <assigned_to name="Thomas Herchenroeder">thron7</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>26678</commentid>
            <who name="Uwe Stahl">uwe.stahl</who>
            <bug_when>2011-09-05 11:48:19 +0200</bug_when>
            <thetext>We have just updated to the newest trunk version (28596) of qooxdoo.

After having done this update, we get the following exception when running the generator script:

File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/bin/generator.py&quot;, line 255, in &lt;module&gt; main() 
File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/bin/generator.py&quot;, line 238, in main generatorObj.run() 
File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/pylib/generator/Generator.py&quot;, line 506, in run CodeProvider.runProvider(script, self) 
File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/pylib/generator/action/CodeProvider.py&quot;, line 47, in runProvider  _handleI18N(script, generator) 
File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/pylib/generator/action/CodeProvider.py&quot;, line 187, in _handleI18N addUntranslatedEntries=True) 
File &quot;/opt/swishudson/inst/swis/workspace/ip-frontend_qooxdoo-provider_release/qooxdoo-provider/target/qx-checkout/tool/pylib/generator/action/Locale.py&quot;, line 237, in getTranslationData 
classList = [x.id for x in clazzList] 
AttributeError: &#39;unicode&#39; object has no attribute &#39;id&#39;

The problem seems to be the revision 28577 of the file Locale.py.
The data structure of clazzList has been changed (see http://qooxdoo.svn.sourceforge.net/viewvc/qooxdoo/trunk/qooxdoo/tool/pylib/generator/action/Locale.py?r1=27905&amp;r2=28577), but the file which passes this data structure (CodeProvider.py) was not changed for 8 weeks.

It looks like an inconsitent check-in of a refactored data structure.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>26679</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2011-09-05 12:23:44 +0200</bug_when>
            <thetext>Yes, this was an oversight by me. Thanks for the good analysis.

Fixed with r28603.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>26680</commentid>
            <who name="Uwe Stahl">uwe.stahl</who>
            <bug_when>2011-09-05 12:38:04 +0200</bug_when>
            <thetext>This fix has solved my problem.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37186</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:21:10 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>