<bug>
          <bug_id>5652</bug_id>
          
          <creation_ts>2011-09-28 13:03:00 +0200</creation_ts>
          <short_desc>API generation error</short_desc>
          <delta_ts>2014-03-03 15:25:57 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.apidata</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>1.5.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Stefan Andersson">dev</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="Daniel Wagner">daniel.wagner</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>27009</commentid>
            <who name="Stefan Andersson">dev</who>
            <bug_when>2011-09-28 13:03:58 +0200</bug_when>
            <thetext>first following documentation about Selenium (qooxdoo)...

cd component/simulator
./generate.py api

then...

----------------------------------------------------------------------------
    Initializing: simulator
----------------------------------------------------------------------------
&gt;&gt;&gt; Processing configuration
  - Warning: ! Shadowing job &quot;simulation-run&quot; with local one
  - Warning: ! Shadowing job &quot;simulation-run-source&quot; with local one

----------------------------------------------------------------------------
    Executing: api::apiconf::build-resources
----------------------------------------------------------------------------
&gt;&gt;&gt; Scanning libraries  
&gt;&gt;&gt; Collecting classes   
  - Sorting 411 classes  
&gt;&gt;&gt; Copying resources...
&gt;&gt;&gt; Done (0m36.05)

----------------------------------------------------------------------------
    Executing: api::apiconf::build-script
----------------------------------------------------------------------------
&gt;&gt;&gt; Scanning libraries  
&gt;&gt;&gt; Collecting classes   
  - Sorting 416 classes  
&gt;&gt;&gt; Generate application
  - Processing 1 locales  
  - Generate packages  
  - Generate loader script
&gt;&gt;&gt; Done (0m23.63)

----------------------------------------------------------------------------
    Executing: api::apiconf::build-files
----------------------------------------------------------------------------
&gt;&gt;&gt; Copying application files...
&gt;&gt;&gt; Done (0m00.08)

----------------------------------------------------------------------------
    Executing: api::apiconf::build-data
----------------------------------------------------------------------------
&gt;&gt;&gt; Scanning libraries  
&gt;&gt;&gt; Collecting classes   
  - Warning: Hint: Unknown global symbol referenced: simulator.TestRunner (simulator.reporter.Application:39)
  - Warning: Hint: Unknown global symbol referenced: testrunner.runner.TestRunnerBasic (simulator.Application:46)
  - Processing explicitly configured includes/excludes...
  - Sorting 761 classes  
&gt;&gt;&gt; Collecting classes   
  - Warning: Hint: Unknown global symbol referenced: simulator.TestRunner (simulator.reporter.Application:39)
  - Warning: Hint: Unknown global symbol referenced: testrunner.runner.TestRunnerBasic (simulator.Application:46)
  - Processing explicitly configured includes/excludes...
  - Sorting 761 classes  
&gt;&gt;&gt; Generating API data...
  - Loading class docs... 90%      - Failed: Missing name of parameter., Line: 62, Column: 31

Error: Error in API data of class: simulator.Application
100%
Error: Found erroneous API information. Please see above. Stopping!
  - Done (0m56.57)

--------

The error message is not giving any advice at all what is wrong. Is the error occurring in file Application?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>27011</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2011-09-28 13:43:15 +0200</bug_when>
            <thetext>Thanks for the report. The Generator shows more information about the error in verbose mode (-v):

    - Extracting API data: simulator.Application...
      - Failed: Missing name of parameter., Line: 62, Column: 31
Error: Error in API data of class: simulator.Application
100%
Error: Found erroneous API information. Please see above. Stopping!</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>27013</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2011-09-28 13:50:29 +0200</bug_when>
            <thetext>Fixed for trunk and branch_1_5_x with r28803.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>38930</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:25:57 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>