<bug>
          <bug_id>5688</bug_id>
          
          <creation_ts>2011-10-06 17:02:00 +0200</creation_ts>
          <short_desc>No error or warning when two functions with same name in same class</short_desc>
          <delta_ts>2013-12-16 12:45:43 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>DUPLICATE</resolution>
          <dup_id>4561</dup_id>
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Stefan Andersson">dev</reporter>
          <assigned_to name="Unassigned">none</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>27123</commentid>
            <who name="Stefan Andersson">dev</who>
            <bug_when>2011-10-06 17:02:27 +0200</bug_when>
            <thetext>The following code gives no error or warning at generation time:


qx.Class.define(&quot;z.demo.Application&quot;,
{
  extend : qx.application.Standalone,

  /*
  *****************************************************************************
     MEMBERS
  *****************************************************************************
  */

  members :
  {
    /**
     * This method contains the initial application code and gets called 
     * during startup of the application
     * 
     * @lint ignoreDeprecated(alert)
     */
    main : function()
    {
      // Call super class
      this.base(arguments);

      // Enable logging in debug variant
      if (qx.core.Environment.get(&quot;qx.debug&quot;))
      {
        // support native logging capabilities, e.g. Firebug for Firefox
        qx.log.appender.Native;
        // support additional cross-browser console. Press F7 to toggle visibility
        qx.log.appender.Console;
      }

      /*
      -------------------------------------------------------------------------
        Below is your actual application code...
      -------------------------------------------------------------------------
      */

    },

    createButtonPane : function()
    {
    },

    createButtonPane : function()
    {
    }
  }
});</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>27124</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2011-10-06 18:35:18 +0200</bug_when>
            <thetext>&#39;generate.py lint&#39; catches this.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>27185</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2011-10-12 10:30:58 +0200</bug_when>
            <thetext>So this will be fixed with bug #4561.

*** This bug has been marked as a duplicate of bug 4561 ***</thetext>
          </long_desc>
      
      

    </bug>